# Generated by Django 6.0.3 on 2026-03-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('late_threshold_minutes', models.IntegerField(default=15)),
                ('report_delay_hours', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['shift_start'],
            },
        ),
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='users.user')),
            ],
            options={
                'verbose_name': 'User Shift Assignment',
                'verbose_name_plural': 'User Shift Assignments',
                'ordering': ['-effective_from'],
                'unique_together': {('user', 'effective_from')},
            },
        ),
    ]
