# Generated by Django 6.0.3 on 2026-03-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField()),
                ('action', models.CharField(choices=[('came', 'Keldi'), ('gone', 'Ketdi')], max_length=10)),
                ('photo', models.FileField(upload_to='attendance/%Y/%m/%d/')),
                ('face_confidence', models.FloatField()),
                ('terminal_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='users.user')),
            ],
            options={
                'verbose_name': 'Attendance Event',
                'verbose_name_plural': 'Attendance Events',
                'ordering': ['scanned_at'],
            },
        ),
    ]
