# Generated by Django 6.0.3 on 2026-03-27 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('shifts', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('notify_on_came', models.BooleanField(default=True)),
                ('notify_on_gone', models.BooleanField(default=True)),
                ('notify_on_report_sent', models.BooleanField(default=True)),
                ('notify_on_report_failed', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Admin Notification Config',
                'verbose_name_plural': 'Admin Notification Configs',
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('computed_came_at', models.DateTimeField(blank=True, null=True)),
                ('computed_gone_at', models.DateTimeField(blank=True, null=True)),
                ('work_minutes', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('incomplete', 'Incomplete')], max_length=20)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('came_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='came_session', to='attendance.attendanceevent')),
                ('gone_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gone_session', to='attendance.attendanceevent')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shifts.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_sessions', to='users.user')),
            ],
            options={
                'verbose_name': 'Work Session',
                'verbose_name_plural': 'Work Sessions',
                'ordering': ['-session_date'],
                'unique_together': {('user', 'session_date')},
            },
        ),
    ]
